# Generated by Django 4.1.1 on 2022-10-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название чата', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания чата')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления чата')),
            ],
        ),
    ]
