# Generated by Django 4.1.1 on 2022-10-09 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Текст сообщения', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания сообщения')),
                ('author', models.ForeignKey(help_text='Автор сообщения', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(help_text='Чат сообщения', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats_app.chat')),
            ],
        ),
    ]
