# Generated by Django 4.1.1 on 2022-10-09 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats_app', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True, help_text='Дата присоединения к чату')),
                ('chat', models.ForeignKey(help_text='Пользователь чата', on_delete=django.db.models.deletion.CASCADE, related_name='member_chats', to='chats_app.chat')),
                ('inviter', models.ForeignKey(help_text='Пригласитель', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_invites', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='Пользователь чата', on_delete=django.db.models.deletion.CASCADE, related_name='chat_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_members',
            field=models.ManyToManyField(help_text='Пользователи чата', through='chats_app.MemberChat', to=settings.AUTH_USER_MODEL),
        ),
    ]
