# Generated by Django 4.1.1 on 2022-10-08 10:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Количество баллов за работу', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField(help_text='Комментарий к оценке')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_assessments', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название практической работы', max_length=80, unique=True)),
                ('description', models.TextField(help_text='Описание практической работы')),
                ('students', models.ManyToManyField(related_name='student_works', through='education_app.Assessment', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='teacher_works', through='education_app.Assessment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='work',
            field=models.ForeignKey(help_text='Оцениваемая практическая работа студента', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='education_app.work'),
        ),
    ]
